In [2]:
import torch

In [3]:
from data_prep import Password as P

In [6]:
a = torch.randn(2,1,3)

In [7]:
sm = torch.nn.Softmax(dim = 2)

In [8]:
a = sm(a)

In [9]:
a

tensor([[[0.4938, 0.3191, 0.1871]],

        [[0.1675, 0.1992, 0.6332]]])

In [10]:
b = [2, 1, 0]
b = torch.LongTensor(b)
b

tensor([2, 1, 0])

In [11]:
b.unsqueeze_(-1)
b

tensor([[2],
        [1],
        [0]])

In [12]:
c = torch.nn.NLLLoss()

In [13]:
c(a[1], b[1])

tensor(-0.1992)

In [14]:
a

tensor([[[0.4938, 0.3191, 0.1871]],

        [[0.1675, 0.1992, 0.6332]]])

In [15]:
b

tensor([[2],
        [1],
        [0]])

In [97]:
x = torch.tensor([1,-1], dtype=torch.float, requires_grad=True)
y = torch.tensor([3,5], dtype=torch.float, requires_grad=True)
a = 2 * x.dot(y) + y

In [98]:
print(x)
print(y)

tensor([ 1., -1.], requires_grad=True)
tensor([3., 5.], requires_grad=True)


In [99]:
a.backward(torch.ones_like(a))

In [100]:
print(x.grad)

tensor([12., 20.])


In [1]:
import logging
logging.basicConfig(format='%(asctime)s - %(filename)s[line:%(lineno)d] - %(levelname)s: %(message)s',
                    level=logging.DEBUG,
                    filename='test.log',
                    filemode='a')
logging.debug("test")